name: release version

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: maven package release
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          git config --global user.email "foo@bar.com"
          git config --global user.name "Maven Release"
          git fetch origin main
          git checkout main
          git pull
          git fetch --tags
          current_tag=$(git tag | head -1)
          git tag -d $current_tag
          git push --delete origin $current_tag

          echo "Maven prepare begin"
          mvn -B -DskipTests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
          -Darguments="-DskipTests -Dmaven.javadoc.skip=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.deploy.skip=true -Dmaven.javadoc.skip=true" \
          -DreleaseVersion=$current_tag \
          -Dtag=$current_tag \
          -DdevelopmentVersion=$current_tag-SNAPSHOT \
          release:prepare

          echo "Maven release begin"
          mvn -B -DskipTests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
          -Darguments="-DskipTests -Dmaven.javadoc.skip=true -Dmaven.javadoc.skip=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.javadoc.skip=true" \
          release:perform
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MAVEN_SSH_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


