name: release version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: maven package release
        run: |
          echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
          mvn -B release:prepare -Darguments="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
          mvn -B release:perform -Darguments="-Dmaven.javadoc.skip=true"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MAVEN_SSH_PRIVATE_KEY }}


